services:
  - type: web
    name: rv32icongestionpred
    runtime: python
    rootDir: congestion_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
